site_title = "DoctorFocusAreas"
limit_days = 3652
cache_url = "https://derekdlp.github.io/DoctorFocusAreas/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 150
category = "cs.CY"
title = "Computers and Society"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.SI"
title = "Social and Information Networks"

[[sources]]
limit = 150
category = "stat.ML"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
